# Generated by Django 2.2.16 on 2023-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'ordering': ('-created',),
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(
                help_text='Введите текст', verbose_name='текст'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(
                help_text='Введите текст', verbose_name='текст'
            ),
        ),
    ]
